# You have to configure this ###################################################
title: Octopod
url: http://127.0.0.1:4000
# You should configure this ####################################################
subtitle: podcasting for geeks
description: My super duper cool podcast.
author: Uncle Octopod
email: octopod@example.com
keywords: [octopod, podcast, magic]
itunes_categories: [Technology]
# You can configure this #######################################################
language: en
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY-NC-SA 3.0
exclude:
- Gemfile
- Rakefile
